name: Continious Integration
run-name: CI

on:
  push:
    branches: main
    paths-ignore: "*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Time suite
        run: |
          echo "Running Tests"
          sleep 5
          exit 0
        
