name: Variable and Secrets

on: workflow_dispatch

jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo "REPO VARIABLE: $ENV_REPO_VAR"
          echo "DIR VARIABKE:" ${{vars.REPO_VARIABLE}}
          echo "STEP VARIABE:" $STEP_VAR
        env:
          ENV_REPO_VAR: ${{vars.REPO_VARIABLE}}
          STEP_VAR: 'This is a step variable'

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Experiemtning
        run: |
          echo "REPO SECRET"" $ENV_REPO_SEC
          echo "DIRECT SEC :" ${{secrets.REPO_SECRET}}
        env:
          ENV_REPO_SEC: ${{secrets.REPO_SECRET}}
          
